export const SITE_NAME = 'Vitalidad Masculina'
export const SITE_URL = 'https://www.vitalidadmasculina.com.ar'
export const MEDICO_NOMBRE = 'Dr. Leandro Mateu'
export const DEVELOPER_NAME = 'FrandoWeb'
export const DEVELOPER_URL = 'https://frandoweb.com/'
export const WHATSAPP_NUMBER = '' // TODO: completar cuando el cliente lo provea
export const CONTACT_EMAIL = '' // TODO: completar cuando el cliente lo provea
export const INSTAGRAM_URL = '' // TODO: completar cuando el cliente lo provea
export const CONSULTORIO_ZONA = 'Palermo, CABA'
